### ISSUE TITLE
编译过程提前退出，U-boot编译失败

### ISSUE THREAD

**Issue by h1k0n** [chainsx/armbian-riscv-build#1]
编译日志输出：
```
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [scripts/Makefile.host:106: scripts/dtc/dtc] Error 1
make[1]: *** [scripts/Makefile.build:436: scripts/dtc] Error 2
make: *** [Makefile:571: scripts] Error 2
```

**Comment by chainsx** [comment]
推荐用 ubuntu 20.04，升级一下 binutils

**Comment by h1k0n** [comment]
![1685090006274](https://github.com/chainsx/armbian-riscv-build/assets/11515010/ee303d89-780f-4007-b5f0-a7f04ef1e59d)

可不可以在patch中加入一些代码呢

**Comment by chainsx** [comment]
这是是在 Lichee Pi 4A 上面遇到的吗？
你可以在 patch/u-boot 下新建 thead-current 目录，
把 patch 放进去。
或者是直接去 [这里](https://github.com/chainsx/thead-u-boot) 提 PR。

**Comment by chainsx** [comment]
> 这是是在 Lichee Pi 4A 上面遇到的吗？ 你可以在 patch/u-boot 下新建 thead-current 目录， 把 patch 放进去。 或者是直接去 [这里](https://github.com/chainsx/thead-u-boot) 提 PR。

我更建议是这样

**Comment by chainsx** [comment]
已经在 u-boot 仓库中进行修改了
