### ISSUE TITLE
内核源码无法自定义修改

### ISSUE THREAD

**Issue by ixgbe** [chainsx/armbian-riscv-build#10]
您好，当前执行在Licheepi4A上执行sudo ./compile.sh  BOARD=licheepi-4a BRANCH=current RELEASE=jammy BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=yes COMPRESS_OUTPUTIMAGE=sha,gpg,xz 正常编译之后，修改内核源码，再次执行sudo ./compile.sh  BOARD=licheepi-4a BRANCH=current RELEASE=jammy BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=yes COMPRESS_OUTPUTIMAGE=sha,gpg,xz编译命令，发现自己本地修改的内核源码又和远程的内核源码对齐了，自己的修改被 还原了。能否优化一下项目，使其在第一次执行编译命令拉取交叉编译工具链、内核源码之后，第二次执行时，不再去拉取。使用户可以自定义修改内核源码。

**Comment by chainsx** [comment]
1.  你是指内核配置吗？每次配置前会加载默认内核配置。你可以保存每次自己自定义的内核配置来替换 `armbian-riscv-build/config/kernel/linux-thead-current.config`

2.  交叉编译工具链只会在第一次拉取，如果不需要优化编译工具链，可以使用 https://github.com/armbian/build，该项目使用 apt-get 安装的 gcc-riscv64-linux-gnu 进行内核编译。

3.  这个仓库相关标准参考 https://github.com/armbian/build 以方便向上游提交补丁，
暂不会考虑修改策略

**Comment by ixgbe** [comment]
感谢您的答复。我指的是armbian-riscv-build/cache/sources/linux-riscv目录下的lpi4a,  lpi4a是内核源码。修改这个里的某个内核源码文件，编译时会自动与远程代码仓库对齐，导致本地修改失效。
编译armbian时候，脚本拉取内核源码的链接:  https://github.com/revyos/thead-kernel

**Comment by chainsx** [comment]
你可以把这里改为自定义后的仓库地址：
https://github.com/chainsx/armbian-riscv-build/blob/main/config/sources/families/thead.conf#L27
