### ISSUE TITLE
针对LicheePi4A 有没有适配Armbian linux 6.1 内核的计划

### ISSUE THREAD

**Issue by ixgbe** [chainsx/armbian-riscv-build#11]
您好，针对LicheePi4A 有没有适配Armbian linux 6.1 内核的计划呢？谢谢。

**Comment by chainsx** [comment]
您好，
1.  官方 Armbian 以及这个仓库实现的是构建过程，
2.  官方 Armbian 以及这个仓库使用官方提供的 BSP 内核（在 LicheePi 4A 上是 [T-Head 提供的 5.10](https://github.com/revyos/thead-kernel)）或者基于主线的内核（目前在 LicheePi 4A 上是 [6.6-rc5 ~ 6.6-rc7](https://github.com/revyos/th1520-linux-kernel)），所使用内核与 Armbian 和本仓库无太大关联。
3.  LicheePi 4A 主线化尚未完成，功能有缺失，不是进行 backport 的时机。
4.  我不是官方人员，LicheePi 4A 也是自费购买，目前的进展完全是爱好驱使。
5.  实在需要 backport 到 6.1 内核的话，麻烦寻求 Sipeed/T-Head 进行帮助。

**Comment by ixgbe** [comment]
好的，非常感谢您的回复。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 青菜萝卜冬瓜 ***@***.***&gt;
发送时间: 2023年10月27日 17:21
收件人: chainsx/armbian-riscv-build ***@***.***&gt;
抄送: ixgbe ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [chainsx/armbian-riscv-build] 针对LicheePi4A 有没有适配Armbian linux 6.1 内核的计划 (Issue #11)





 
您好，
  
官方 Armbian 以及这个仓库实现的是构建过程，
 
官方 Armbian 以及这个仓库使用官方提供的 BSP 内核（在 LicheePi 4A 上是 T-Head 提供的 5.10）或者基于主线的内核（目前在 LicheePi 4A 上是 6.6-rc5 ~ 6.6-rc7），所使用内核与 Armbian 和本仓库无太大关联。
 
LicheePi 4A 主线化尚未完成，功能有缺失，不是进行 backport 的时机。
 
我不是官方人员，LicheePi 4A 也是自费购买，目前的进展完全是爱好驱使。
 
实在需要 backport 到 6.1 内核的话，麻烦寻求 Sipeed/T-Head 进行帮助。
