### ISSUE TITLE
荔枝派Armbian系统起不来

### ISSUE THREAD

**Issue by ixgbe** [chainsx/armbian-riscv-build#4]
![cacdbbda6612b838001830c6a3e8365](https://github.com/chainsx/armbian-riscv-build/assets/27911713/720c41e0-71b7-46a1-a9f4-42c73ca6cb5e)

荔枝派，用的是自己编译出来的镜像(最新的源码) +  [u-boot-with-spl.bin](https://github.com/chainsx/armbian-riscv-build/releases/download/20230720-1320/u-boot-with-spl.bin)

编译命令
sudo ./compile.sh  BOARD=licheepi-4a BRANCH=current RELEASE=jammy BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=yes COMPRESS_OUTPUTIMAGE=sha,gpg,xz

下载的源码:   https://github.com/chainsx/armbian-riscv-build.git

但是用release提供的 https://github.com/chainsx/armbian-riscv-build/releases/download/20230720-1320/Armbian_23.05.15-riscv_Licheepi-4a_jammy_current_5.10.113.img.xz  和 [u-boot-with-spl.bin](https://github.com/chainsx/armbian-riscv-build/releases/download/20230720-1320/u-boot-with-spl.bin)  armbian就可以起来

**Comment by chainsx** [comment]
最近 revyos 内核源码改了包创建相关的代码，导致我之前提供的 patch 失效，会尽快修复。

 tips: LicheePi 4A 我提交了 Armbian 官方支持。

**Comment by ixgbe** [comment]
感谢你的回复，我试一下Armbian 官方的看看。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chainsx/armbian-riscv-build"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月28日(星期一) 晚上9:03
***@***.***&gt;;
抄送:&nbsp;"yangwang ***@***.******@***.***&gt;;
主题:&nbsp;Re: [chainsx/armbian-riscv-build] 荔枝派Armbian系统起不来 (Issue #4)





 
最近 revyos 内核源码改了包创建相关的代码，导致我之前提供的 patch 失效，会尽快修复。
 
tips: LicheePi 4A 我提交了 Armbian 官方支持。

**Comment by chainsx** [comment]
已经确认是上游修改内核软件包配置导致补丁打不上，现在已经修复，感谢你的反馈！

**Comment by ixgbe** [comment]
thanks
