### ISSUE TITLE
ATF_USE_GCC is unset

### ISSUE THREAD

**Issue by tsaotse** [chainsx/armbian-riscv-build#5]
commit 6d45c52
ATF_USE_GCC is unset

[ o.k. ] Extension manager [ processed 1 Extension Methods calls and 1 Extension Method implementations ]                                                                                  
[ error ] ERROR in function source [ main.sh:381 -> configuration.sh:416 -> general.sh:0 ]
[ error ] Error in configuration: ATF_USE_GCC is unset 
[ o.k. ] Process terminated 

![image](https://github.com/chainsx/armbian-riscv-build/assets/78033148/009621ce-a98e-4e6e-8983-cd6829f0c625)

**Comment by chainsx** [comment]
Thank you for your feedback. The issue has been fixed.

https://github.com/chainsx/armbian-riscv-build/commit/b600f16806d94f8d9ef7597dca58213b85e7c510
