### ISSUE TITLE
u-boot-with-spl.bin  目前在本项目的Release中并不存在

### ISSUE THREAD

**Issue by ixgbe** [chainsx/armbian-riscv-build#8]
u-boot-with-spl.bin  目前在本项目的Release中并不存在，能否在 Release中提供一下最新的u-boot-with-spl.bin； 或者在LicheePi 4A 安装方法中说明一下如何得到最新的 u-boot-with-spl.bin 。   感谢感谢！！！

**Comment by chainsx** [comment]
不好意思，晚些修改一下说明：
8GB 和 16GB 的 u-boot 可以在这里下载：

https://github.com/chainsx/fedora-riscv-builder/releases/tag/20230914-0456
